info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /product:
    get:
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      tags:
      - 商品列表
  /user/getUserList:
    get:
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户模块
  /user/modifyPassword:
    get:
      parameters:
      - description: 密码
        in: query
        name: password
        type: string
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: 修改用户密码
      tags:
      - 用户模块
  /user/register:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 重复密码
        in: query
        name: rePassword
        type: string
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
swagger: "2.0"
